# Generated by Django 2.2.5 on 2022-02-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CREC', 'Creche'), ('PRIM1', 'Primary 1'), ('PRIM2', 'Primary 2'), ('PRIM3', 'Primary 3'), ('PRIM4', 'Primary 4'), ('PRIM5', 'Primary 5'), ('PRIM6', 'Primary 6'), ('JHS1', 'JHS 1'), ('JHS2', 'JHS 2'), ('JHS3', 'JHS 3')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=36)),
                ('last_name', models.CharField(max_length=36)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('score', models.IntegerField()),
                ('attitude_remark', models.TextField(max_length=100)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('leave', models.BooleanField(default=False)),
                ('offday', models.BooleanField(default=False)),
                ('remarks', models.TextField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Subject')),
            ],
        ),
    ]
