# Generated by Django 2.2.5 on 2022-02-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('CREC', 'Creche'), ('PRIM1', 'Primary 1'), ('PRIM2', 'Primary 2'), ('PRIM3', 'Primary 3'), ('PRIM4', 'Primary 4'), ('PRIM5', 'Primary 5'), ('PRIM6', 'Primary 6'), ('JHS1', 'JHS 1'), ('JHS2', 'JHS 2'), ('JHS3', 'JHS 3')], max_length=5),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
